### ISSUE TITLE
This Activity already has an action bar supplied by the window decor

### ISSUE THREAD

**Issue by vagprogrammer** [bkhezry/ExtraWebView#1]
Hi! thanks for providing this great tool, but i can not use correctly, every i want to launch the WebView this error ocurr:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxxxxxx/com.github.bkhezry.extrawebview.ItemActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by bkhezry** [comment]
Hi,
this library used `android.support.v7.widget.Toolbar` for toolbar.
if you use custom theme, please add `parent="Theme.AppCompat.NoActionBar"` to your style tag.

**Comment by vagprogrammer** [comment]
Thanks, now it works without any problems. Now proceed to close this "Issue"

**Comment by netoliguz91** [comment]
Thanks a lot dude, you'd save my project

**Comment by am9072** [comment]
There are **two simple and quick solutions**

go to res-->values-->styles
watch the simple video for the answer
[https://youtu.be/YJR8njVHRA4](url)

You can  remove your window action bar by setting NoActionBar 
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`
or by adding  <item name="windowActionBar">false</item>
    <item name="windowNoTitle">true</item>
